### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by oliverlj** [evert/bigint-money#32]
Included it in a ember project: add i got this issue :+1: 
```
ERROR in ./node_modules/bigint-money/dist/util.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /home/oliver/git/fritzy-front/node_modules/bigint-money/dist/util.js: Identifier directly after number (10:24)

   8 | exports.PRECISION = BigInt(exports.PRECISION_I);
   9 | // Multiplication factor for internal values
> 10 | exports.PRECISION_M = 10n ** exports.PRECISION;
     |                         ^
  11 | var Round;
  12 | (function (Round) {
  13 |     // The following rules are round to the nearest integer, but have different
    at Parser.raise (/home/oliver/git/fritzy-front/node_modules/@babel/parser/lib/index.js:7044:17)
    at Parser.readNumber (/home/oliver/git/fritzy-front/node_modules/@babel/parser/lib/index.js:7979:18)
    at Parser.getTokenFromCode (/home/oliver/git/fritzy-front/node_modules/@babel/parser/lib/index.js:7686:14)
    at Parser.nextToken (/home/oliver/git/fritzy-front/node_modules/@babel/parser/lib/index.js:7268:12)
    at Parser.next (/home/oliver/git/fritzy-front/node_modules/@babel/parser/lib/index.js:7197:10)
    at Parser.parseMaybeAssign (/home/oliver/git/fritzy-front/node_modules/@babel/parser/lib/index.js:9096:12)
    at Parser.parseExpression (/home/oliver/git/fritzy-front/node_modules/@babel/parser/lib/index.js:9017:23)
    at Parser.parseStatementContent (/home/oliver/git/fritzy-front/node_modules/@babel/parser/lib/index.js:10853:23)
    at Parser.parseStatement (/home/oliver/git/fritzy-front/node_modules/@babel/parser/lib/index.js:10724:17)
    at Parser.parseBlockOrModuleBlockBody (/home/oliver/git/fritzy-front/node_modules/@babel/parser/lib/index.js:11298:25)
```

**Comment by evert** [comment]
This library will _only_ work in javascript engines that support `bigint`. Given that this error is thrown in Babel, likely means that you are using an older Babel or you need some plugin to support this.

If you're not directly using babel, but some other package that depends on it, you might also simply be out of date. My first step would therefore just be: make sure your dependencies are up to date.

bigint is a pretty new feature.

**Comment by oliverlj** [comment]
Hi, thanks for your answer, i'm on last version of babel 7.8 but bigint need a plugin to support 10n.

**Comment by evert** [comment]
I'm assuming I can close this then. As an aside, I can't imagine why you need Babel. If you're doing stuff with bigint, you will need pretty modern browsers
